// Command genadapters writes internal/adapters/all/all.go, which blank-imports every adapter package so a binary
// that imports "all" has every provider registered. Run it through go generate from the module root:
//
//	go generate ./internal/adapters/all
package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
)

const module = "github.com/lineofflight/frankfurter/go"

func main() {
	root, err := moduleRoot()
	if err != nil {
		log.Fatal(err)
	}
	dir := filepath.Join(root, "internal", "adapters")
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatal(err)
	}
	var pkgs []string
	for _, e := range entries {
		if !e.IsDir() || e.Name() == "all" {
			continue
		}
		if files, _ := filepath.Glob(filepath.Join(dir, e.Name(), "*.go")); len(files) > 0 {
			pkgs = append(pkgs, e.Name())
		}
	}
	sort.Strings(pkgs)

	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./cmd/genadapters; DO NOT EDIT.\n\n")
	b.WriteString("package all\n\nimport (\n")
	for _, p := range pkgs {
		b.WriteString("\t_ \"" + module + "/internal/adapters/" + p + "\"\n")
	}
	b.WriteString(")\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "all", "all.go"), src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("imported %d adapter packages", len(pkgs))
}

// moduleRoot walks up from the working directory to go.mod.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}
