// Command providerhealth is bin/provider_health.rb, the provider health monitor.
//
// It fetches the live /v2/providers feed and flags missed publishes or unknown currency codes, keeping one GitHub issue
// per affected provider. This surfaces silent freezes and published labels that need a currency registry update.
//
// Issues carry two labels: `provider` (the umbrella every provider issue shares, human-filed or auto) and `health`
// (bot-owned; the discriminator used to find the rolling issues this command manages). `health` must never be applied
// by hand, or this command could match and edit a human's issue.
//
// `publishes_missed` is already cadence-aware in its unit (missed fire days for daily, missed buckets for weekly and
// monthly), computed server-side, so this only thresholds it. Thresholds sit above normal lag: daily absorbs holiday
// clusters and T+1 publishing; monthly absorbs in-arrears archives.
//
// Each run, per flagged provider: create an issue if none is open, otherwise refresh its body (so the missed count
// stays current) without commenting. When all checks recover, its issue is commented and closed. Creation is the only
// notification; an ongoing freeze stays quiet.
//
// Run with DRY_RUN=1 to print the decision and bodies without touching issues.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	healthLabel   = "health"
	providerLabel = "provider"
)

// thresholds flag only well past normal lag.
var thresholds = map[string]int{"daily": 8, "weekly": 2, "monthly": 2}

// Entry is one provider in the /v2/providers feed, reduced to what health checks read.
type Entry struct {
	Key               string   `json:"key"`
	Name              string   `json:"name"`
	PublishCadence    string   `json:"publish_cadence"`
	PublishesMissed   *int     `json:"publishes_missed"`
	EndDate           string   `json:"end_date"`
	UnknownCurrencies []string `json:"unknown_currencies"`
}

func (e Entry) missed() int {
	if e.PublishesMissed == nil {
		return 0
	}
	return *e.PublishesMissed
}

func stale(e Entry) bool {
	threshold, ok := thresholds[e.PublishCadence]
	return ok && e.missed() >= threshold
}

// flagged keeps stale providers and those with unknown codes, most missed first.
func flagged(entries []Entry) []Entry {
	var out []Entry
	for _, e := range entries {
		if stale(e) || len(e.UnknownCurrencies) > 0 {
			out = append(out, e)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].missed() > out[j].missed() })
	return out
}

// marker is the stable identifier embedded in each issue body, deliberately kept as `provider-health` (not renamed
// with the label) so already-open issues stay matchable. It pins an issue to its provider, independent of labels.
func marker(key string) string { return "<!-- provider-health: " + key + " -->" }

var markerRe = regexp.MustCompile(`<!-- provider-health: (\w+) -->`)

func renderBody(e Entry, today string) string {
	sections := []string{marker(e.Key), fmt.Sprintf("**%s** (`%s`)", e.Name, e.Key)}
	if stale(e) {
		sections = append(sections, "This provider has missed more scheduled publishes than normal lag allows. Likely a "+
			"broken feed (TLS, source change, block), not a holiday gap.\n\n"+
			"| Cadence | Last rate | Missed |\n"+
			"|---------|-----------|--------|\n"+
			fmt.Sprintf("| %s | %s | %d |", e.PublishCadence, e.EndDate, e.missed()))
	}
	if len(e.UnknownCurrencies) > 0 {
		codes := make([]string, len(e.UnknownCurrencies))
		for i, c := range e.UnknownCurrencies {
			codes[i] = "`" + c + "`"
		}
		sections = append(sections, "Unknown currency codes: "+strings.Join(codes, ", ")+".\n\n"+
			"These quotes are stored and available through provider routes, but excluded from blends and the currency "+
			"catalogue. Check the published labels and add verified entries to `db/seeds/currency_patches.json` or "+
			"update the Money gem.")
	}
	sections = append(sections, "_Checked "+today+" UTC. Auto-generated by `.github/workflows/provider-health.yml`; "+
		"closes when all checks recover._")
	return strings.Join(sections, "\n\n") + "\n"
}

type auditor struct {
	repo       string
	today      string
	dryRun     bool
	stderr     io.Writer
	fetch      func(ctx context.Context) ([]Entry, error)
	openIssues func(ctx context.Context) (map[string]int, error)
	gh         func(ctx context.Context, args ...string) (string, error)
}

func (a auditor) run(ctx context.Context) error {
	entries, err := a.fetch(ctx)
	if err != nil {
		return err
	}
	flaggedEntries := flagged(entries)

	if a.dryRun {
		keys := make([]string, len(flaggedEntries))
		for i, e := range flaggedEntries {
			keys[i] = e.Key
		}
		fmt.Fprintf(a.stderr, "DRY_RUN flagged: %q\n", keys)
		for _, e := range flaggedEntries {
			fmt.Fprintln(a.stderr, renderBody(e, a.today))
		}
		return nil
	}

	open, err := a.openIssues(ctx)
	if err != nil {
		return err
	}
	var flaggedKeys []string
	for _, e := range flaggedEntries {
		flaggedKeys = append(flaggedKeys, e.Key)
		body := renderBody(e, a.today)
		title := "Stale provider: " + e.Key
		if len(e.UnknownCurrencies) > 0 {
			title = "Unknown currencies: " + e.Key
		}
		if number, ok := open[e.Key]; ok {
			_, err = a.gh(ctx, "issue", "edit", strconv.Itoa(number), "--repo", a.repo, "--title", title, "--body", body)
		} else {
			_, err = a.gh(ctx, "issue", "create", "--repo", a.repo, "--label", providerLabel, "--label", healthLabel,
				"--title", title, "--body", body)
		}
		if err != nil {
			return err
		}
	}

	var recovered []string
	for key := range open {
		if !slices.Contains(flaggedKeys, key) {
			recovered = append(recovered, key)
		}
	}
	slices.Sort(recovered)
	for _, key := range recovered {
		number := strconv.Itoa(open[key])
		if _, err := a.gh(ctx, "issue", "comment", number, "--repo", a.repo, "--body",
			key+" passes provider health checks again. Closing."); err != nil {
			return err
		}
		if _, err := a.gh(ctx, "issue", "close", number, "--repo", a.repo); err != nil {
			return err
		}
	}
	return nil
}

func gh(ctx context.Context, args ...string) (string, error) {
	out, err := exec.CommandContext(ctx, "gh", args...).Output()
	if err != nil {
		return "", fmt.Errorf("gh %s failed: %w", strings.Join(args, " "), err)
	}
	return string(out), nil
}

// openIssuesByKey maps each open health issue to the provider it tracks.
func openIssuesByKey(ctx context.Context, repo string) (map[string]int, error) {
	out, err := gh(ctx, "issue", "list", "--repo", repo, "--state", "open", "--label", healthLabel, "--json",
		"number,body", "--limit", "100")
	if err != nil {
		return nil, err
	}
	var issues []struct {
		Number int    `json:"number"`
		Body   string `json:"body"`
	}
	if err := json.Unmarshal([]byte(out), &issues); err != nil {
		return nil, err
	}
	byKey := map[string]int{}
	for _, issue := range issues {
		if m := markerRe.FindStringSubmatch(issue.Body); m != nil {
			byKey[m[1]] = issue.Number
		}
	}
	return byKey, nil
}

// fetchProviders reads the feed, retrying network failures three times with exponential backoff.
func fetchProviders(ctx context.Context, api string) ([]Entry, error) {
	for attempt := 1; ; attempt++ {
		entries, err := getProviders(ctx, api)
		var netErr net.Error
		if err == nil || !errors.As(err, &netErr) || attempt > 3 {
			return entries, err
		}
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(time.Duration(1<<attempt) * time.Second):
		}
	}
}

func getProviders(ctx context.Context, api string) ([]Entry, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, api, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var entries []Entry
	if err := json.NewDecoder(resp.Body).Decode(&entries); err != nil {
		return nil, fmt.Errorf("decode %s: %w", api, err)
	}
	return entries, nil
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func main() {
	api := getenv("API", "https://api.frankfurter.dev/v2/providers")
	repo := getenv("REPO", "lineofflight/frankfurter")
	a := auditor{
		repo:       repo,
		today:      time.Now().Format(time.DateOnly),
		dryRun:     os.Getenv("DRY_RUN") != "",
		stderr:     os.Stderr,
		fetch:      func(ctx context.Context) ([]Entry, error) { return fetchProviders(ctx, api) },
		openIssues: func(ctx context.Context) (map[string]int, error) { return openIssuesByKey(ctx, repo) },
		gh:         gh,
	}
	if err := a.run(context.Background()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
