// Code generated by go run ./cmd/genadapters; DO NOT EDIT.

package all

import (
	_ "github.com/lineofflight/frankfurter/go/internal/adapters/banrep"
	_ "github.com/lineofflight/frankfurter/go/internal/adapters/bnr"
	_ "github.com/lineofflight/frankfurter/go/internal/adapters/jpc"
	_ "github.com/lineofflight/frankfurter/go/internal/adapters/rbv"
)
