name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  discussion_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

concurrency:
  group: claude-code-${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number || github.run_id }}
  cancel-in-progress: false

jobs:
  claude-readonly:
    if: >
      (
        (github.event_name == 'issue_comment' &&
         contains((github.event.comment.body || ''), '@claude')) ||
        (github.event_name == 'pull_request_review_comment' &&
         contains((github.event.comment.body || ''), '@claude')) ||
        (github.event_name == 'discussion_comment' &&
         contains((github.event.comment.body || ''), '@claude')) ||
        (github.event_name == 'pull_request_review' &&
         contains((github.event.review.body || ''), '@claude')) ||
        (github.event_name == 'issues' &&
         (contains((github.event.issue.body || ''), '@claude') ||
          contains((github.event.issue.title || ''), '@claude')))
      )
      && !contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'),
           (github.event.comment.author_association || github.event.review.author_association || github.event.issue.author_association))
      && !endsWith(github.actor, '[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      discussions: read
      actions: read
      # id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code (Read-only)
        id: claude-readonly
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          claude_args: >-
            --model claude-opus-4-1-20250805
            --allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"

  claude-write:
    if: >
      (
        (github.event_name == 'issue_comment' &&
         contains((github.event.comment.body || ''), '@claude')) ||
        (github.event_name == 'pull_request_review_comment' &&
         contains((github.event.comment.body || ''), '@claude')) ||
        (github.event_name == 'discussion_comment' &&
         contains((github.event.comment.body || ''), '@claude')) ||
        (github.event_name == 'pull_request_review' &&
         contains((github.event.review.body || ''), '@claude')) ||
        (github.event_name == 'issues' &&
         (contains((github.event.issue.body || ''), '@claude') ||
          contains((github.event.issue.title || ''), '@claude')))
      )
      && contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'),
           (github.event.comment.author_association || github.event.review.author_association || github.event.issue.author_association))
      && !endsWith(github.actor, '[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for commits/branches
      pull-requests: write
      issues: write
      discussions: write
      actions: read # for CI context
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code (Full Access)
        id: claude-write
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          prompt: |
            You have full repository access as a trusted collaborator.
            Read the user's @claude mention and execute precisely.
            For batch ops:
            - Track items with TodoWrite
            - Process all items
            - Retry failures; note any that remain
            - Summarize completed vs failed at the end
          claude_args: >-
            --model claude-opus-4-1-20250805
            --allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*),Bash(gh issue close:*),Bash(gh issue create:*),Bash(gh pr create:*),Bash(gh pr close:*),Bash(gh api:*)"
