name: Test Auto-merge dependabot PRs
on: 
  pull_request_target:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to test'
        required: true
        type: number

permissions:
  pull-requests: write
  contents: write

jobs:
  test-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR URL
        id: pr_url
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "PR_URL=https://github.com/${{ github.repository }}/pull/${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Test PR info
        run: |
          echo "Testing PR: ${{ steps.pr_url.outputs.PR_URL }}"
          gh pr view "${{ steps.pr_url.outputs.PR_URL }}" --json number,title,state,author
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Test auto-merge command (dry run)
        run: |
          echo "Would run: gh pr merge --auto --squash ${{ steps.pr_url.outputs.PR_URL }}"
          gh pr view "${{ steps.pr_url.outputs.PR_URL }}" --json mergeable,mergeStateStatus,statusCheckRollup
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}